# Generated by Django 4.2.1 on 2023-05-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hallname', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=50)),
                ('matricnumber', models.CharField(default='', max_length=10, unique=True)),
                ('players', models.CharField(default='', max_length=10)),
                ('sport', models.CharField(default='', max_length=20)),
                ('brackettype', models.CharField(default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
